---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-thumbnails4j
  description: Buildkite Pipeline for thumbnails4j
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/thumbnails4j

spec:
  type: buildkite-pipeline
  owner: group:enterprise-search
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: thumbnails4j
    spec:
      repository: elastic/thumbnails4j
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        # your-team:
        #  access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
