## 🏠/.buildkite/deploy_snapshot_pipeline.yml
# snapshot deployment pipeline - runs once per day

agents:
  image: "docker.elastic.co/ci-agent-images/enterprise-search/thumbnails4j-buildkite-agent"
  ephemeralStorage: "20G"
  memory: "4G"
  useVault: true

notify:
  - if: 'build.branch =~ /^((main)|([0-9]+\.[0-9]+))\$/ && (build.state == "failed" || pipeline.started_passing)'
    slack:
      channels:
        - "#search-et-alerts"
      message: "${BUILDKITE_MESSAGE}"

steps:
  - label: ":truck: Maven Deploy Snapshot"
    command: ".buildkite/scripts/run_deploy_release.sh deploy"
    timeout_in_minutes: 45
